export default {
  icon_GoongMap: require("@app/assets/images/icon-GoongMap.png"),

  spinner: require("@app/assets/images/loader1.gif"),

  username: require("@app/assets/images/username.png"),
  password: require("@app/assets/images/password.png"),

  // Order
  background_OverDetail: require("@app/assets/images/backgroundOverDetail.png"),
  back_ic: require("@app/assets/images/icon/arrow_left.png"),

  closeX: require("@app/assets/images/Close.png"),
  weather: require("@app/assets/images/icon/weather.png"),
  plus: require('@app/assets/images/icon/plus.png'),
  minus: require('@app/assets/images/icon/minus.png'),
  box: require('@app/assets/images/icon/box.png'),
  location: require('@app/assets/images/icon/location.png'),
  routeArrow: require('@app/assets/images/icon/route_arrow.png'),
  route: require('@app/assets/images/icon/route.png'),
  menu: require('@app/assets/images/icon/menu.png'),
  menuText: require('@app/assets/images/icon/menu_text.png'),
  search: require('@app/assets/images/icon/search.png'),
  frame: require('@app/assets/images/icon/Frame.png'),
  music: require('@app/assets/images/icon/music.png'),
  star: require('@app/assets/images/icon/star.png'),
  account: require('@app/assets/images/icon/account.png'),
  setting: require('@app/assets/images/icon/setting.png'),
  close: require('@app/assets/images/icon/close.png'),
  arrowLeftSearch: require('@app/assets/images/icon/arrowLeftSearch.png'),
  eatDrink: require('@app/assets/images/icon/eat_drink.png'),
  hotel: require('@app/assets/images/icon/hotel.png'),
  seatSing: require('@app/assets/images/icon/sight_sing.png'),
  gasStation: require('@app/assets/images/icon/gas_station.png'),
  entertainment: require('@app/assets/images/icon/entertainment.png'),
  home: require('@app/assets/images/icon/home.png'),
  agency: require('@app/assets/images/icon/agency.png'),
  favorites: require('@app/assets/images/icon/favorites.png'),
  historyTime: require('@app/assets/images/icon/history_time.png'),
  direction: require('@app/assets/images/icon/direction.png'),
  closeDirection: require('@app/assets/images/icon/close_direction.png'),
  trafficLight: require('@app/assets/images/icon/traffic_light.png'),
  currentLocation: require('@app/assets/images/icon/current_location.png'),
  share: require('@app/assets/images/icon/share.png'),
  way: require('@app/assets/images/icon/way.png'),
  backgroundLocation: require('@app/assets/images/icon/background_locationInfo.png'),
  arrowLocation: require('@app/assets/images/icon/arrow_locationInfo.png'),
  arrowBack: require('@app/assets/images/icon/arrowLeftBack.png'),
  backgroundFavoritePlace: require('@app/assets/images/icon/background_FavoritePlace.png'),
  frequently: require('@app/assets/images/icon/frequently.png'),
  homeFavorite: require('@app/assets/images/icon/HomeFavorite.png'),
  starFavorite: require('@app/assets/images/icon/StarFavorite.png'),
  businessFavorite: require('@app/assets/images/icon/BusinessFavorite.png'),
  thereVertical: require('@app/assets/images/thereVertical.png'),
  extraLocation: require('@app/assets/images/icon/extraLocation.png'),
  fixLocation: require('@app/assets/images/icon/fix_location.png'),
  deleteLocation: require('@app/assets/images/icon/delete_location.png'),
  starGold: require('@app/assets/images/star_gold.png'),
  ellipse: require('@app/assets/images/ellipse.png'),
  vector: require('@app/assets/images/vector.png'),
  weather: require('@app/assets/images/weather.png'),
  markerLocation: require('@app/assets/images/marker_location.png'),
  movingHistory: require('@app/assets/images/icon/move_history.png'),
  user: require('@app/assets/images/icon/User.png'),
  calendar: require('@app/assets/images/icon/Calendar.png'),
  closeMovingHistory: require('@app/assets/images/x_circle_icon_174835.png'),
  fiveVerticalDots: require('@app/assets/images/fiveVerticalDots.png'),
  brownCircle: require('@app/assets/images/brownCircle.png'),


  list: require('@app/assets/images/icon/list.png'),
  icPlay: require('@app/assets/images/ic_play.png'),
  icPause: require('@app/assets/images/ic_pause.png'),
  icNext: require('@app/assets/images/ic_next.png'),
  icPrev: require('@app/assets/images/ic_prev.png'),
  ic_whiteArrow: require('@app/assets/images/ic_whiteArrow.png'),
  icArrowUp: require('@app/assets/images/ic_arrowup.png'),
  logoVov: require('@app/assets/images/logo_vov.png'),
  vov: require('@app/assets/images/vov.png'),
  vovGTHN: require('@app/assets/images/vovGT.png'),
  vovGTTPHCM: require('@app/assets/images/vovGT.png'),
  vovGTMekong: require('@app/assets/images/vovGT.png'),
  vov1: require('@app/assets/images/vov1.png'),
  vov2: require('@app/assets/images/vov2.png'),
  vov3: require('@app/assets/images/vov3.png'),
  vov4: require('@app/assets/images/vov4.png'),
  vov6: require('@app/assets/images/vov6.png'),
  vovTV: require('@app/assets/images/vovTV.png'),
  mapDisplay: require('@app/assets/images/ic_map.png'),
  warning: require('@app/assets/images/ic_warningAlert.png'),
  system: require('@app/assets/images/ic_system.png'),
  language: require('@app/assets/images/ic_language.png'),
  blackClose: require('@app/assets/images/ic_blackClose.png'),
  vi: require('@app/assets/images/language/ic_vi.png'),
  en: require('@app/assets/images/language/ic_en.png'),
  icCar: require('@app/assets/images/ic_car.png'),
  greySearch: require('@app/assets/images/grey_search.png'),
  success: require('@app/assets/images/success.png'),
  boldClose: require('@app/assets/images/close_bold.png'),
  voice: require('@app/assets/images/voice.png'),
  warningBlue: require('@app/assets/images/warning.png'),
  camera: require('@app/assets/images/camera.png'),
  video: require('@app/assets/images/video.png'),
  trafficLight: require('@app/assets/images/traffic_light.png'),
  district: require('@app/assets/images/district.png'),
  screenShot: require('@app/assets/images/camera_screen_shot.png'),
  cameraLocation: require('@app/assets/images/camera_location.png'),
  my: require('@app/assets/images/language/ic_bu.png'),
  locationBlue: require('@app/assets/images/location.png'),
  fullScreen: require('@app/assets/images/full_screen.png'),
  normalScreen: require('@app/assets/images/normal_screen.png'),

  //icon order
  filter: require("@app/assets/images/Filterfilter.png"),
  dropdowIcon: require("@app/assets/images/dropdownIcon.png"),
  leftArrow: require("@app/assets/images/leftArrow.png"),
  xTag: require("@app/assets/images/xTag.png"),
  check: require("@app/assets/images/check.png"),

  infoTab: require("@app/assets/images/Frameinfo.png"),


  readNoti: require("@app/assets/images/readNoti.png"),

  trashRed: require("@app/assets/images/trashred.png"),
  download: require("@app/assets/images/download.png"),
  eyeBlue: require("@app/assets/images/eyeblue.png"),

  excelIcon: require("@app/assets/images/excel.png"),
  fileIcon: require("@app/assets/images/file.png"),
  dotBar: require("@app/assets/images/dotBar.png"),

  addNavigation: require("@app/assets/images/route/add_navigation.png"),
  selectedCar: require("@app/assets/images/route/selected_car.png"),
  centerNavigation: require("@app/assets/images/route/center_navigation.png"),
  fromNavigation: require("@app/assets/images/route/from_navigation.png"),
  unSelectedBike: require("@app/assets/images/route/un_selected_motor.png"),
  swapNavigation: require("@app/assets/images/route/swap_navigation.png"),
  toNavigation: require("@app/assets/images/route/to_navigation.png"),
  voidNavigation: require("@app/assets/images/route/void_navigation.png"),
  backNavigation: require("@app/assets/images/route/back_navigation.png"),
  routeNavigation: require("@app/assets/images/route/route_navigation.png"),
  selectedBike: require("@app/assets/images/route/selected_motor.png"),
  unSelectedCar: require("@app/assets/images/route/un_selected_car.png"),
  locationRoute: require("@app/assets/images/route/location.png"),
  myLocation: require("@app/assets/images/route/my_location.png"),
  arrowRight: require("@app/assets/images/route/arrow_right.png"),
  selectedTaxi: require("@app/assets/images/route/selected_taxi.png"),
  unSelectedTaxi: require("@app/assets/images/route/un_selected_taxi.png"),
  detailsRoute: require("@app/assets/images/route/details_route.png"),
  darkMapStyle: require("@app/assets/images/mapStyles/darkMapStyle.png"),
  lightMapStyle: require("@app/assets/images/mapStyles/lightMapStyle.png"),
  nightMapStyle: require("@app/assets/images/mapStyles/nightMapStyle.png"),
  normalMapStyle: require("@app/assets/images/mapStyles/normalMapStyle.png"),
  satelliteMapStyle: require("@app/assets/images/mapStyles/satelliteMapStyle.png"),
  upArrow: require("@app/assets/images/icon/up_arrow.png"),
  downArrow: require("@app/assets/images/icon/down_arrow.png"),
  hand: require("@app/assets/images/hand.png"),
  arriveEnd: require("@app/assets/images/routeDetails/arrive_end.png"),
  arriveLeft: require("@app/assets/images/routeDetails/arrive_left.png"),
  arriveRight: require("@app/assets/images/routeDetails/arrive_right.png"),
  arriveStart: require("@app/assets/images/routeDetails/arrive_start.png"),
  departLeft: require("@app/assets/images/routeDetails/depart_left.png"),
  departRight: require("@app/assets/images/routeDetails/depart_right.png"),
  goStraight: require("@app/assets/images/routeDetails/go_straight.png"),
  slightLeft: require("@app/assets/images/routeDetails/slight_left.png"),
  slightRight: require("@app/assets/images/routeDetails/slight_right.png"),
  turning: require("@app/assets/images/routeDetails/turning.png"),
  turnLeft: require("@app/assets/images/routeDetails/turn_left.png"),
  turnRight: require("@app/assets/images/routeDetails/turn_right.png"),
  alert: require("@app/assets/images/icon/alert.png"),
  empty: require("@app/assets/images/empty.png"),
  startRoute: require("@app/assets/images/route/start_route.png"),
  markerRouting: require("@app/assets/images/route/marker_routing.png"),

  turningStep: require("@app/assets/images/routingStep/turning.png"),
  clock: require("@app/assets/images/route/clock.png"),
  distance: require("@app/assets/images/route/distance.png"),
  parking: require("@app/assets/images/route/parking.png"),
  gas: require("@app/assets/images/route/gas.png"),
  eat: require("@app/assets/images/route/eat.png"),
  addLocation: require("@app/assets/images/route/add_location.png"),
  percent: require("@app/assets/images/route/percent.png"),
  tick: require("@app/assets/images/route/tick.png"),
  logo: require("@app/assets/images/route/logo.png"),
  upArrowWhite: require("@app/assets/images/route/up_arrow.png"),
  question: require("@app/assets/images/icon/question.png"),
  twoDots: require("@app/assets/images/route/two_dots.png"),
  healthy: require("@app/assets/images/route/healthy.png"),
  navigation: require("@app/assets/images/route/navigation.png"),
  myLocationButton: require("@app/assets/images/route/my_location_button.png"),


  //sandtable
  loginBg: require("@app/assets/images/projects/login_bg.jpg"),
  logoDark: require("@app/assets/images/projects/logo_dark.png"),

};
