import { StyleSheet } from 'react-native';

const ProjectDetailStyles = StyleSheet.create({
  header: {
    paddingVertical: 2,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    // gap: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    zIndex: 99,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  projectName: {
    fontSize: 12,
    fontWeight: '500',
  },
  projectDate: {
    fontSize: 10,
    fontWeight: '500',
    color: '#555',
  },
  memberDropdown: {
    position: 'absolute',
    // top: 90,
    right: 48,
    backgroundColor: '#fff',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 6,
    paddingVertical: 8,
    width: 240,
    maxHeight: 240,
    zIndex: 999,
    // pointerEvents: 'auto',
  },
  memberItem: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomColor: '#f0f0f0',
    borderBottomWidth: 1,
    backgroundColor: '#fff',
    borderRadius: 8,
    marginHorizontal: 4,
    marginVertical: 2,
  },
  memberName: {
    fontWeight: '600',
    fontSize: 14,
    color: '#333',
  },
  memberInfo: {
    fontSize: 12,
    color: '#888',
    marginTop: 2,
  },
  actionButton: {
    width: 36,
    height: 36,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  actionList: {
    position: 'absolute',
    top: 40,
    right: 10,
    zIndex: 1000,
    alignItems: 'flex-end',
  },
});
export default ProjectDetailStyles;